# Generated by Django 4.0 on 2021-12-14 21:23

import channels.views
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Failed'), (1, 'Success'), (2, 'Pre Run'), (3, 'Processing')], default=2)),
                ('channel', models.CharField(choices=[('EmailChanel', channels.views.EmailChanel), ('LinkedInChannel', channels.views.LinkedInChannel)], max_length=20)),
                ('rule', models.JSONField()),
                ('execution_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('action', models.CharField(max_length=10)),
                ('params', models.JSONField()),
                ('type', models.CharField(choices=[('CLICK', 'Click'), ('OPEN', 'Open')], max_length=10)),
            ],
        ),
    ]
